title: Lauren Kowalski  # your name (or website title) here
logo: "/images/lakheadshot.jpg?raw=true" # your photo (or logo) here
description: McMurdo Station, Antarctica, 2023.

  Graduate Student in Physical Oceanography

  Graduate School of Oceanography

  <a href="https://www.linkedin.com/in/lauren-kowalski-57949a125/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
